version: "3.9"
services:

  user:
    build: "./User/"
    ports:
      - 8080:8080
    container_name: "user-api"

  gps:
    build: "./GPS/"
    ports:
      - 8081:8081
    container_name: "gps-api"

  rewards:
    build: "./Reward/"
    ports:
      - 8082:8082
    container_name: "reward-api"

  trip-pricer:
    build: "./TripPricer/"
    ports:
      - 8083:8083
    container_name: "trip-pricer-api"